name: context

on:
  workflow_dispatch:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  var: variableFromWorkflow

jobs:
  job1: 
    name: JOB 1
    runs-on: ubuntu-latest
    env:
      var: variableFrom_JOB1

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: env variables job1
        run: echo "${{env.var}}"

      - name: multiline env variables job1
        run: |
          echo $var
          echo ${{env.var}}

          echo ""
  job2:
    name: JOB 2
    runs-on: ubuntu-latest
    steps:
      - name: env variables job2
        run: echo "${{env.var}}"

      - name: multiline env variables job2
        run: |
          echo $var
          echo ${{env.var}}

          echo "here"

  job3:
    name: special env variables
    runs-on: ubuntu-latest
    steps:
      - name: summary
        run: |
          echo "## Build and Test Summary" >> $GITHUB_STEP_SUMMARY
          cat $GITHUB_STEP_SUMMARY
          
      - name: workflow vars
        run: echo "${{ github.workflow }}" "${{ github.run_id }}" "${{ github.run_number }}" "${{ github.sha }}"

      - name: others
        run: echo "${{ github.actor }}" "${{ github.repository }}"

        
      
  
