name: context

on:
  workflow_dispatch:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  var: variableFromWorkflow

jobs:
  job1: 
    name: JOB 1
    runs-on: ubuntu-latest
    env:
      var: variableFrom_JOB1

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: env variables
        run: echo "${{env.var}}"

      - name: env variables 2
        run: |
          echo $var
          echo ${{env.var}}

          echo ""

      
  
