name: context

on:
  workflow_dispatch:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  job1: 
    name: JOB 1
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
