name: Jobs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:


jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
  
    steps:
      - name: Run Hello world
        run: echo Hello world

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: run job 2
        run: echo Job2 running
      - name: exit job 2
        run: exit 0

  job3:
    name: Job 3
    runs-on: ubuntu-latest
    if: always()
    needs:
      - job1
      - job2
    steps:
      - name: run job 3
        run: echo Job3 is running HELLO

  
      
      
